/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.canes.view;

import com.app.canes.dao.ProdutoDAO;
import com.app.canes.model.Produto;
import com.app.canes.model.Usuario;
import com.app.canes.util.ConfirmUtil;
import com.app.canes.util.PermissaoUtil;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Carlos Borges
 */
public class ProdutoView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProdutoView.class.getName());
    private Usuario usuarioLogado;
    /**
     * Creates new form menu
     */
    public ProdutoView() {

        carregarTela();

        initComponents();
        
        

    }
    public ProdutoView(Usuario usuarioLogado){
        
        this.usuarioLogado = usuarioLogado;
        
         carregarTela();

        initComponents();
        
        this.setLayout(null);
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/canes-.png"));
        JLabel lblImagem = new JLabel(icon);

        lblImagem.setBounds(20, 20, 206, 161); // posicione
        this.add(lblImagem);

        carregarTabelaProdutos();
        
        PermissaoUtil.aplicarPermissoes(usuarioLogado,btnCadastrar, btnAtualizar, btnDeletar);
        txtUsuarioLogado.setText(usuarioLogado.getNome());
        txtSetor.setText(usuarioLogado.getSetor());
    }
    ProdutoDAO produtoDAO = ProdutoDAO.getInstance();

    private void carregarTela() {
        JPanel fundo = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon img = new ImageIcon(getClass().getResource("/img/fundo.png"));
                g.drawImage(img.getImage(), 0, 0, getWidth(), getHeight(), this);
            }
        };
        setContentPane(fundo);  // depois aplica o fundo
    }

    public void carregarTabelaProdutos() {

        JTableHeader header = tblProdutos.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 14));
        header.setOpaque(false);
        header.setBackground(new Color(32, 136, 203));
        header.setForeground(Color.WHITE);

        DefaultTableModel model = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID", "Código", "Produto", "Valor", "Quantidade"
                }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return true; // impede edição na tabela
            }
        };
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        tblProdutos.setModel(model);

        for (Produto p : produtoDAO.findAll()) {
            model.addRow(new Object[]{
                p.getId(),
                p.getCodigo(),
                p.getNome(),
                nf.format(p.getValor()),
                p.getEstoque()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 1), new java.awt.Dimension(0, 1), new java.awt.Dimension(32767, 1));
        jLabel3 = new javax.swing.JLabel();
        btnDeletar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        txtUsuarioLogado = new javax.swing.JLabel();
        txtSetor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Produto");

        btnDeletar.setBackground(new java.awt.Color(224, 38, 38));
        btnDeletar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletar.setText("Deletar");
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletar.setVerifyInputWhenFocusTarget(false);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(50, 48, 48));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setVerifyInputWhenFocusTarget(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(50, 48, 48));
        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.setVerifyInputWhenFocusTarget(false);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(50, 48, 48));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.setVerifyInputWhenFocusTarget(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProdutos.setRowHeight(25);
        jScrollPane1.setViewportView(tblProdutos);

        txtUsuarioLogado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuarioLogado.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarioLogado.setText("1");

        txtSetor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSetor.setForeground(new java.awt.Color(255, 255, 255));
        txtSetor.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(467, 467, 467))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(159, 159, 159)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txtUsuarioLogado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSetor)))
                .addGap(65, 65, 65)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeletar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnVoltar)
                    .addComponent(btnCadastrar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        
        if (ConfirmUtil.confirmarExclusao(this)) {
            int row = tblProdutos.getSelectedRow();

            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Selecione um produto!");
                return;
            }

// O ID está na coluna 0 da tabela
            Integer id = (Integer) tblProdutos.getModel().getValueAt(row, 0);

// Deleta usando o DAO
            produtoDAO.delete(id);

// Recarrega a tabela
            carregarTabelaProdutos();

            JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        ProdutoCadastro view = new ProdutoCadastro(this);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
        view.setTitle("CADASTRO");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        int row = tblProdutos.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione uma linha para atualizar!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblProdutos.getModel();

        // ID é sempre número
        Integer id = Integer.parseInt(model.getValueAt(row, 0).toString());

        Produto p = produtoDAO.findById(id);

        if (p == null) {
            JOptionPane.showMessageDialog(this,
                    "Erro: Produto não encontrado!",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // ✔ Nome (String)
        p.setNome(model.getValueAt(row, 2).toString());

        // ✔ Código (int)
        try {
            p.setCodigo(Integer.parseInt(model.getValueAt(row, 1).toString()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Código inválido! Digite apenas números.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // ✔ Valor (double)
        try {
            String valor = model.getValueAt(row, 3).toString().replaceAll("[^0-9,]", "").replace(",", ".");

            p.setValor(Double.parseDouble(valor));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Valor inválido! Use formato 99.99",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // ✔ Estoque (int)
        try {
            p.setEstoque(Integer.parseInt(model.getValueAt(row, 4).toString()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Estoque inválido! Digite apenas números.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Salvar no DAO
        produtoDAO.save(p);

        JOptionPane.showMessageDialog(this,
                "Produto atualizado com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE
        );

        carregarTabelaProdutos();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Menu view = new Menu(usuarioLogado);
        view.setLocationRelativeTo(null);
        view.setVisible(true);
        view.setTitle("MENU");
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProdutoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JLabel txtSetor;
    private javax.swing.JLabel txtUsuarioLogado;
    // End of variables declaration//GEN-END:variables
}
